--年度根据实际情况进行调整，该文件以2016-》2017年为例
insert into  gfm_ps_pre_pfs
select balance_id,
       budget_amount,
       budget_add_amount,
       budget_add_amounting,
       budget_sub_amount,
       budget_sub_amounting,
       assign_add_amount,
       assign_add_amounting,
       assign_sub_amount,
       assign_sub_amounting,
       modulate_add_amount,
       modulate_add_amounting,
       modulate_sub_amount,
       modulate_sub_amounting,
       quota_amount,
       quota_back_amount,
       stock_plan_amount,
       pay_amount,
       ps_pfs_id,
       prj_code,
       2016 as set_year,
       0 as business_year,
       stock_flag,
       pfs_detail_content,
       prj_budget_type_id,
       prj_budget_kind_id,
       bgt_source_id,
       exp_func_id,
       exp_eco_id,
       quota_level_id,
       agency_id,
       in_mof_dep_id,
       mof_dep_id,
       in_ps_agency_id,
       surplus_flag,
       puritem_id,
       rcid,
       prj_std_id,
       10220 as bill_type_id,
       pay_flag,
       is_assign,
       last_ver,
       create_date,
       create_user,
       ele_hold1_id,
       ele_hold2_id,
       ele_hold3_id,
       ele_hold4_id,
       ele_hold5_id,
       ele_hold6_id,
       ele_hold7_id,
       ele_hold8_id,
       ele_hold9_id,
       ele_hold10_id,
       n_field5,
       n_field4,
       n_field3,
       n_field2,
       n_field1,
       c_field5,
       c_field4,
       c_field3,
       c_field2,
       c_field1,
       financing_type_id,
       0 as financing_company_id,
       0 as inv_balance_id,
       0 as sum_financing_amount,
       nvl(((nvl(a.budget_amount, 0) + nvl(a.budget_add_amount, 0) +
           nvl(a.assign_add_amount, 0) + nvl(a.modulate_add_amount, 0)) -
           (nvl(a.budget_sub_amount, 0) + nvl(a.budget_sub_amounting, 0) +
           nvl(a.assign_sub_amount, 0) + nvl(a.assign_sub_amounting, 0) +
           nvl(a.modulate_sub_amount, 0) +
           nvl(a.modulate_sub_amounting, 0) + nvl(a.inv_pay_amount, 0) +
           nvl(a.stock_plan_amount, 0) + nvl(a.carry_over_amounting, 0) +
           nvl(a.carry_over_amount, 0))),
           0) as pfs_amount,
       (select (select max(balance_id) from 2016.gfm_ps_pfs_balance) +
               (select value
                  from gap_no_seq q
                 where q.seq_name = 'SEQ_GFM_PFS_NUM') - a.balance_id
          from dual) as id,
       (select m.id from gfm_ps_main m where m.prj_code = a.prj_code) as bill_id,
       fundsource_id,
       charge_detail_id,
       0 as gov_fund_category_id,
       budget_dyl_flag,
       0 as enterprise_support_flag,
       0 as basic_spending_flag,
       0 as agricultural_subsidies_flag,
       0 as governmental_funds_flag,
       doc_no_id,
       doc_no_name,
       0 as trans_bill_id,
       (select p.prj_fundsource_id from gfm_ps_prj_balance p where p.balance_id=a.prj_balance_id) as prj_fundsource_id,
       spend_kind_id
  from 2016.gfm_ps_pfs_balance a;
